name: example
publish_to: "none"

environment:
  sdk: ^3.3.0

dependencies:
  zef_di_abstractions: ^1.1.1

  zef_di_inglue: ^1.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

  build_runner:

  zef_di_abstractions_generator:
    path: ../
