name: example
publish_to: "none"

environment:
  sdk: ^3.0.5

dependencies:
  #zef_di_abstractions: ^2.0.0
  zef_di_abstractions:
    path: ../../ZEF_DI_Abstractions

  #zef_di_inglue: ^1.1.1
  zef_di_inglue:
    path: ../../ZEF_DI_Inglue

  zef_helpers_lazy: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

  build_runner:

  zef_di_abstractions_generator:
    path: ../
