name: example
publish_to: "none"

environment:
  sdk: ^3.3.0

dependencies:
  zef_di_abstractions:
    path: ../../ZEF_DI_Abstractions

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

  build_runner:

  zef_di_abstractions_generator:
    path: ../
